### ISSUE TITLE
word2vec error :  tensorflow.python.framework.errors_impl.NotFoundError: /root/project/embed/tf/optimized/word2vec_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by lemo2012** [tensorflow/models#2966]
I ran the word2vec example and got the error.

Environment:
(1) centos7
(2) python3
(3) cpu

Any solution for this problem?  Thank you in advance!

**Comment by thinkin3d** [comment]
I also get the same error when trying to run word2vec_optimized.py with a g++ built word2vec_ops.so.  Attempting to use tensorflow binaries from both pip installed tensorflow-gpu, and building from source with branch r1.4 (in separate virtualenvs).

Environment:
- Ubuntu 16.04
- Python 3.5.2
- g++ 5.4.0

```
$ echo $TF_INC
/ai/tensorflow.ai/env3/lib/python3.5/site-packages/tensorflow/include
```
```
$ g++ -std=c++11 -shared word2vec_ops.cc word2vec_kernels.cc -o word2vec_ops.so -fPIC -I $TF_INC -O2 -D_GLIBCXX_USE_CXX11_ABI=0
```
```
$ ls -a
.   __init__.py  questions-words.txt  text8                word2vec_ops.cc  word2vec_optimized.py       word2vec.py
..  output       README.md            word2vec_kernels.cc  word2vec_ops.so  word2vec_optimized_test.py  word2vec_test.py
```
```
$ python3 word2vec_optimized.py --train_data=text8 --eval_data=questions-words.txt --save_path=output/
Traceback (most recent call last):
  File "word2vec_optimized.py", line 44, in <module>
    word2vec = tf.load_op_library(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'word2vec_ops.so'))
  File "/ai/tensorflow.ai/env3_tf_from_src/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/ai/tensorflow.ai/env3_tf_from_src/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /ai/tensorflow.ai/models/tutorials/embedding/word2vec_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

Please advise!

**Comment by thinkin3d** [comment]
Building without the `-D_GLIBCXX_USE_CXX11_ABI=0` flag makes no difference either, same error.

**Comment by thinkin3d** [comment]
@nealwu @drpngx Any updates or insights on this issue?  I'm currently blocked.  Thanks

**Comment by sseveran** [comment]
I can reproduce this inside the official tensorflow docker image with version 1.4.1. My workaround was to use the 1.2.1 docker image which works fine. I did not try 1.3.

**Comment by drpngx** [comment]
Actually, the current version should be 1.5.x. Couldyou try that?

**Comment by drpngx** [comment]
Are you using the monolithic build or the split out build?

**Comment by PatWie** [comment]
FYI I tried as well 
on the latest commit:
```
commit 4cb0c13c7779da536cac6c682180c5757611b384
Merge: 915105a dc07d56
Author: Frank Chen <frankchn@gmail.com>
Date:   Mon Jan 8 17:00:24 2018 -0800

    Merge pull request #15955 from frankchn/branch_181174976
    
    Branch 181174976
```
using different ways (ABI=0, ABI=1, omit the flag)

```
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_NSYNC=$HOME/.local/lib/python2.7/site-packages/tensorflow/include/external/nsync/public
g++ -std=c++11 -shared word2vec_ops.cc word2vec_kernels.cc -o word2vec_ops.so -fPIC -I $TF_INC -O2 -D_GLIBCXX_USE_CXX11_ABI=0 -I $TF_NSYNC
```

all gives me
```
undefined symbol: _ZTIN10tensorflow8OpKernelE
```

Even in a very basic custom Op (tensorflow/tensorflow#15002)

I will try a build with g++4.9 to make sure to use the old ABI.

**Comment by nealwu** [comment]
Hi all, could you try again with the latest version of the README? We just merged a change to the compile instructions in https://github.com/tensorflow/models/pull/3099.

**Comment by NightFantomJ2** [comment]
@nealwu can confirm the new instructions work (after leaving out the `-D_GLIBCXX_USE_CXX11_ABI=0` because I compiled from source).

relevant specs I can think of:
ubuntu 16.04, 64 bit, anaconda python 3.6.4, tensorflow 1.4.0, gcc 7.2.0

**Comment by joaodafonseca** [comment]
I'm still having the same problem described above! Can't run any of the python scripts.

**Comment by nealwu** [comment]
Hi @joaodafonseca, what problem are you having exactly? Did you run the new instructions at https://github.com/tensorflow/models/tree/master/tutorials/embedding?

**Comment by joaodafonseca** [comment]
Hi @nealwu, yes I did follow the new instructions and having the following errors:
`Traceback (most recent call last):
  File "word2vec_optimized.py", line 44, in <module>
    word2vec = tf.load_op_library(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'word2vec_ops.so'))
  File "/Users/joaofonseca/tensorflow/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/joaofonseca/tensorflow/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/joaofonseca/tensorflow/tensorflow/tensorflow/models/tutorials/embedding/word2vec_ops.so, 6): image not found`

**Comment by nealwu** [comment]
Hi @joaodafonseca, that's a different error from what everyone here was experiencing. It looks like you might have a problem with your Python and/or TensorFlow installation. I recommend asking on StackOverflow for advice.

Closing this issue in the meantime since the original issue has been resolved.
