### ISSUE TITLE
export_tflite_ssd_graph.py gives this error i dint know what to do. How can I convert my model into tflite model

### ISSUE THREAD

**Issue by yahiya6006** [tensorflow/models#9118]
I have trained a custom model which is working fine. It has its checkpoint saved as a ckpt-0.index I tried to convert the saved model (saved in .pb format) using the TFLiteconverter But got Error. After a bit of google search, I found that we need a frozen inference graph for which we should use "export_tflite_ssd_graph.py" but I'm getting this error I don't know what to do.

This is the entire cmd output
C:\Users\CROWN\Documents\Python\tensorflow_object_detection\models\research\object_detection>export_tflite_ssd_graph.py --pipeline_config_path=training/pipeline.config --trained_checkpoint_prefix=inference_graph/checkpoint/ckpt-0 --output_directory inference_graph/tflite --add_postprocessing_op=true
2020-08-17 23:30:48.345133: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-17 23:30:48.355484: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.603165 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.605166 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.606162 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.607163 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.607163 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0817 23:31:03.608167 20136 convolutional_keras_box_predictor.py:153] depth of additional conv before box predictor: 0
2020-08-17 23:31:04.749451: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-08-17 23:31:04.757155: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-17 23:31:04.775137: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: WINDOWS-O7A691R
2020-08-17 23:31:04.782997: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: WINDOWS-O7A691R
2020-08-17 23:31:04.790577: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-17 23:31:04.828975: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2283ceffdf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-17 23:31:04.839345: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0817 23:31:06.853309 20136 deprecation.py:317] From C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from inference_graph/checkpoint/ckpt-0
I0817 23:31:09.562763 20136 saver.py:1293] Restoring parameters from inference_graph/checkpoint/ckpt-0
2020-08-17 23:31:10.399033: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key BoxPredictor/ConvolutionalBoxHead_0/BoxEncodingPredictor/bias not found in checkpoint
WARNING:tensorflow:Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
W0817 23:31:10.500229 20136 saver.py:1319] Restoring an object-based checkpoint using a name-based saver. This may be somewhat fragile, and will re-build the Saver. Instead, consider loading object-based checkpoints using tf.train.Checkpoint().
Traceback (most recent call last):
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor/ConvolutionalBoxHead_0/BoxEncodingPredictor/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 1298, in restore
    sess.run(self.saver_def.restore_op_name,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key BoxPredictor/ConvolutionalBoxHead_0/BoxEncodingPredictor/bias not found in checkpoint
         [[node save/RestoreV2 (defined at \AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\export_tflite_ssd_graph_lib.py:296) ]]

Original stack trace for 'save/RestoreV2':
  File "\Documents\Python\tensorflow_object_detection\models\research\object_detection\export_tflite_ssd_graph.py", line 146, in <module>
    tf.app.run(main)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "\Documents\Python\tensorflow_object_detection\models\research\object_detection\export_tflite_ssd_graph.py", line 139, in main
    export_tflite_ssd_graph_lib.export_tflite_graph(
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\export_tflite_ssd_graph_lib.py", line 296, in export_tflite_graph
    saver = tf.train.Saver(**saver_kwargs)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 836, in __init__
    self.build()
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 876, in _build
    self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 515, in _build_internal
    restore_op = self._AddRestoreOps(filename_tensor, saveables,
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 335, in _AddRestoreOps
    all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 583, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1521, in restore_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CROWN\Documents\Python\tensorflow_object_detection\models\research\object_detection\export_tflite_ssd_graph.py", line 146, in <module>
    tf.app.run(main)
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\Users\CROWN\Documents\Python\tensorflow_object_detection\models\research\object_detection\export_tflite_ssd_graph.py", line 139, in main
    export_tflite_ssd_graph_lib.export_tflite_graph(
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\object_detection\export_tflite_ssd_graph_lib.py", line 298, in export_tflite_graph
    frozen_graph_def = exporter.freeze_graph_with_def_protos(
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 151, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 1324, in restore
    self._object_restore_saver = saver_from_object_based_checkpoint(
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\training\saver.py", line 1700, in saver_from_object_based_checkpoint
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError:

Existing variables not in the checkpoint: global_step, ssd_mobile_net_v2keras_feature_extractor/Conv1/kernel, ssd_mobile_net_v2keras_feature_extractor/Conv_1/kernel, ssd_mobile_net_v2keras_feature_extractor/Conv_1_bn/beta, ssd_mobile_net_v2keras_feature_extractor/Conv_1_bn/gamma, ssd_mobile_net_v2keras_feature_extractor/Conv_1_bn/moving_mean, ssd_mobile_net_v2keras_feature_extractor/Conv_1_bn/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_10_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_10_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_10_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_10_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_10_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_10_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_10_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_10_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_10_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_10_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_10_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_10_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_10_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_10_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_10_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_11_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_11_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_11_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_11_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_11_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_11_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_11_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_11_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_11_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_11_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_11_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_11_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_11_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_11_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_11_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_12_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_12_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_12_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_12_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_12_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_12_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_12_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_12_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_12_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_12_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_12_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_12_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_12_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_12_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_12_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_13_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_13_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_13_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_13_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_13_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_13_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_13_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_13_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_13_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_13_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_13_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_13_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_13_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_13_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_13_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_14_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_14_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_14_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_14_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_14_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_14_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_14_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_14_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_14_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_14_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_14_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_14_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_14_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_14_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_14_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_15_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_15_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_15_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_15_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_15_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_15_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_15_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_15_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_15_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_15_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_15_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_15_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_15_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_15_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_15_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_16_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_16_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_16_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_16_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_16_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_16_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_16_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_16_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_16_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_16_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_16_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_16_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_16_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_16_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_16_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_1_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_1_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_1_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_1_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_1_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_1_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_1_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_1_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_1_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_1_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_1_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_1_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_1_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_1_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_1_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_2_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_2_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_2_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_2_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_2_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_2_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_2_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_2_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_2_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_2_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_2_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_2_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_2_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_2_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_2_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_3_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_3_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_3_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_3_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_3_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_3_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_3_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_3_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_3_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_3_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_3_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_3_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_3_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_3_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_3_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_4_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_4_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_4_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_4_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_4_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_4_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_4_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_4_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_4_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_4_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_4_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_4_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_4_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_4_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_4_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_5_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_5_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_5_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_5_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_5_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_5_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_5_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_5_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_5_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_5_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_5_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_5_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_5_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_5_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_5_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_6_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_6_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_6_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_6_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_6_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_6_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_6_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_6_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_6_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_6_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_6_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_6_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_6_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_6_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_6_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_7_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_7_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_7_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_7_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_7_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_7_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_7_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_7_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_7_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_7_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_7_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_7_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_7_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_7_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_7_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_8_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_8_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_8_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_8_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_8_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_8_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_8_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_8_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_8_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_8_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_8_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_8_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_8_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_8_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_8_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_9_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/block_9_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_9_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_9_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_9_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_9_expand/kernel, ssd_mobile_net_v2keras_feature_extractor/block_9_expand_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_9_expand_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_9_expand_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_9_expand_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/block_9_project/kernel, ssd_mobile_net_v2keras_feature_extractor/block_9_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/block_9_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/block_9_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/block_9_project_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/bn_Conv1/beta, ssd_mobile_net_v2keras_feature_extractor/bn_Conv1/gamma, ssd_mobile_net_v2keras_feature_extractor/bn_Conv1/moving_mean, ssd_mobile_net_v2keras_feature_extractor/bn_Conv1/moving_variance, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_depthwise/depthwise_kernel, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_depthwise_BN/beta, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_depthwise_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_depthwise_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_depthwise_BN/moving_variance, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_project/kernel, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_project_BN/beta, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_project_BN/gamma, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_project_BN/moving_mean, ssd_mobile_net_v2keras_feature_extractor/expanded_conv_project_BN/moving_variance

Variables names when this checkpoint was written which don't exist now: Conv1/kernel, Conv_1/kernel, Conv_1_bn/beta, Conv_1_bn/gamma, Conv_1_bn/moving_mean, Conv_1_bn/moving_variance, block_10_depthwise/depthwise_kernel, block_10_depthwise_BN/beta, block_10_depthwise_BN/gamma, block_10_depthwise_BN/moving_mean, block_10_depthwise_BN/moving_variance, block_10_expand/kernel, block_10_expand_BN/beta, block_10_expand_BN/gamma, block_10_expand_BN/moving_mean, block_10_expand_BN/moving_variance, block_10_project/kernel, block_10_project_BN/beta, block_10_project_BN/gamma, block_10_project_BN/moving_mean, block_10_project_BN/moving_variance, block_11_depthwise/depthwise_kernel, block_11_depthwise_BN/beta, block_11_depthwise_BN/gamma, block_11_depthwise_BN/moving_mean, block_11_depthwise_BN/moving_variance, block_11_expand/kernel, block_11_expand_BN/beta, block_11_expand_BN/gamma, block_11_expand_BN/moving_mean, block_11_expand_BN/moving_variance, block_11_project/kernel, block_11_project_BN/beta, block_11_project_BN/gamma, block_11_project_BN/moving_mean, block_11_project_BN/moving_variance, block_12_depthwise/depthwise_kernel, block_12_depthwise_BN/beta, block_12_depthwise_BN/gamma, block_12_depthwise_BN/moving_mean, block_12_depthwise_BN/moving_variance, block_12_expand/kernel, block_12_expand_BN/beta, block_12_expand_BN/gamma, block_12_expand_BN/moving_mean, block_12_expand_BN/moving_variance, block_12_project/kernel, block_12_project_BN/beta, block_12_project_BN/gamma, block_12_project_BN/moving_mean, block_12_project_BN/moving_variance, block_13_depthwise/depthwise_kernel, block_13_depthwise_BN/beta, block_13_depthwise_BN/gamma, block_13_depthwise_BN/moving_mean, block_13_depthwise_BN/moving_variance, block_13_expand/kernel, block_13_expand_BN/beta, block_13_expand_BN/gamma, block_13_expand_BN/moving_mean, block_13_expand_BN/moving_variance, block_13_project/kernel, block_13_project_BN/beta, block_13_project_BN/gamma, block_13_project_BN/moving_mean, block_13_project_BN/moving_variance, block_14_depthwise/depthwise_kernel, block_14_depthwise_BN/beta, block_14_depthwise_BN/gamma, block_14_depthwise_BN/moving_mean, block_14_depthwise_BN/moving_variance, block_14_expand/kernel, block_14_expand_BN/beta, block_14_expand_BN/gamma, block_14_expand_BN/moving_mean, block_14_expand_BN/moving_variance, block_14_project/kernel, block_14_project_BN/beta, block_14_project_BN/gamma, block_14_project_BN/moving_mean, block_14_project_BN/moving_variance, block_15_depthwise/depthwise_kernel, block_15_depthwise_BN/beta, block_15_depthwise_BN/gamma, block_15_depthwise_BN/moving_mean, block_15_depthwise_BN/moving_variance, block_15_expand/kernel, block_15_expand_BN/beta, block_15_expand_BN/gamma, block_15_expand_BN/moving_mean, block_15_expand_BN/moving_variance, block_15_project/kernel, block_15_project_BN/beta, block_15_project_BN/gamma, block_15_project_BN/moving_mean, block_15_project_BN/moving_variance, block_16_depthwise/depthwise_kernel, block_16_depthwise_BN/beta, block_16_depthwise_BN/gamma, block_16_depthwise_BN/moving_mean, block_16_depthwise_BN/moving_variance, block_16_expand/kernel, block_16_expand_BN/beta, block_16_expand_BN/gamma, block_16_expand_BN/moving_mean, block_16_expand_BN/moving_variance, block_16_project/kernel, block_16_project_BN/beta, block_16_project_BN/gamma, block_16_project_BN/moving_mean, block_16_project_BN/moving_variance, block_1_depthwise/depthwise_kernel, block_1_depthwise_BN/beta, block_1_depthwise_BN/gamma, block_1_depthwise_BN/moving_mean, block_1_depthwise_BN/moving_variance, block_1_expand/kernel, block_1_expand_BN/beta, block_1_expand_BN/gamma, block_1_expand_BN/moving_mean, block_1_expand_BN/moving_variance, block_1_project/kernel, block_1_project_BN/beta, block_1_project_BN/gamma, block_1_project_BN/moving_mean, block_1_project_BN/moving_variance, block_2_depthwise/depthwise_kernel, block_2_depthwise_BN/beta, block_2_depthwise_BN/gamma, block_2_depthwise_BN/moving_mean, block_2_depthwise_BN/moving_variance, block_2_expand/kernel, block_2_expand_BN/beta, block_2_expand_BN/gamma, block_2_expand_BN/moving_mean, block_2_expand_BN/moving_variance, block_2_project/kernel, block_2_project_BN/beta, block_2_project_BN/gamma, block_2_project_BN/moving_mean, block_2_project_BN/moving_variance, block_3_depthwise/depthwise_kernel, block_3_depthwise_BN/beta, block_3_depthwise_BN/gamma, block_3_depthwise_BN/moving_mean, block_3_depthwise_BN/moving_variance, block_3_expand/kernel, block_3_expand_BN/beta, block_3_expand_BN/gamma, block_3_expand_BN/moving_mean, block_3_expand_BN/moving_variance, block_3_project/kernel, block_3_project_BN/beta, block_3_project_BN/gamma, block_3_project_BN/moving_mean, block_3_project_BN/moving_variance, block_4_depthwise/depthwise_kernel, block_4_depthwise_BN/beta, block_4_depthwise_BN/gamma, block_4_depthwise_BN/moving_mean, block_4_depthwise_BN/moving_variance, block_4_expand/kernel, block_4_expand_BN/beta, block_4_expand_BN/gamma, block_4_expand_BN/moving_mean, block_4_expand_BN/moving_variance, block_4_project/kernel, block_4_project_BN/beta, block_4_project_BN/gamma, block_4_project_BN/moving_mean, block_4_project_BN/moving_variance, block_5_depthwise/depthwise_kernel, block_5_depthwise_BN/beta, block_5_depthwise_BN/gamma, block_5_depthwise_BN/moving_mean, block_5_depthwise_BN/moving_variance, block_5_expand/kernel, block_5_expand_BN/beta, block_5_expand_BN/gamma, block_5_expand_BN/moving_mean, block_5_expand_BN/moving_variance, block_5_project/kernel, block_5_project_BN/beta, block_5_project_BN/gamma, block_5_project_BN/moving_mean, block_5_project_BN/moving_variance, block_6_depthwise/depthwise_kernel, block_6_depthwise_BN/beta, block_6_depthwise_BN/gamma, block_6_depthwise_BN/moving_mean, block_6_depthwise_BN/moving_variance, block_6_expand/kernel, block_6_expand_BN/beta, block_6_expand_BN/gamma, block_6_expand_BN/moving_mean, block_6_expand_BN/moving_variance, block_6_project/kernel, block_6_project_BN/beta, block_6_project_BN/gamma, block_6_project_BN/moving_mean, block_6_project_BN/moving_variance, block_7_depthwise/depthwise_kernel, block_7_depthwise_BN/beta, block_7_depthwise_BN/gamma, block_7_depthwise_BN/moving_mean, block_7_depthwise_BN/moving_variance, block_7_expand/kernel, block_7_expand_BN/beta, block_7_expand_BN/gamma, block_7_expand_BN/moving_mean, block_7_expand_BN/moving_variance, block_7_project/kernel, block_7_project_BN/beta, block_7_project_BN/gamma, block_7_project_BN/moving_mean, block_7_project_BN/moving_variance, block_8_depthwise/depthwise_kernel, block_8_depthwise_BN/beta, block_8_depthwise_BN/gamma, block_8_depthwise_BN/moving_mean, block_8_depthwise_BN/moving_variance, block_8_expand/kernel, block_8_expand_BN/beta, block_8_expand_BN/gamma, block_8_expand_BN/moving_mean, block_8_expand_BN/moving_variance, block_8_project/kernel, block_8_project_BN/beta, block_8_project_BN/gamma, block_8_project_BN/moving_mean, block_8_project_BN/moving_variance, block_9_depthwise/depthwise_kernel, block_9_depthwise_BN/beta, block_9_depthwise_BN/gamma, block_9_depthwise_BN/moving_mean, block_9_depthwise_BN/moving_variance, block_9_expand/kernel, block_9_expand_BN/beta, block_9_expand_BN/gamma, block_9_expand_BN/moving_mean, block_9_expand_BN/moving_variance, block_9_project/kernel, block_9_project_BN/beta, block_9_project_BN/gamma, block_9_project_BN/moving_mean, block_9_project_BN/moving_variance, bn_Conv1/beta, bn_Conv1/gamma, bn_Conv1/moving_mean, bn_Conv1/moving_variance, expanded_conv_depthwise/depthwise_kernel, expanded_conv_depthwise_BN/beta, expanded_conv_depthwise_BN/gamma, expanded_conv_depthwise_BN/moving_mean, expanded_conv_depthwise_BN/moving_variance, expanded_conv_project/kernel, expanded_conv_project_BN/beta, expanded_conv_project_BN/gamma, expanded_conv_project_BN/moving_mean, expanded_conv_project_BN/moving_variance, save_counter

(64 variable name(s) did match)

Could not find some variables in the checkpoint (see names above). Saver was attempting to load an object-based checkpoint (saved using tf.train.Checkpoint or tf.keras.Model.save_weights) using variable names. If the checkpoint was written with eager execution enabled, it's possible that variable names have changed (for example missing a '_1' suffix). It's also possible that there are new variables which did not exist when the checkpoint was written. You can construct a Saver(var_list=...) with only the variables which previously existed, and if variable names have changed you may need to make this a dictionary with the old names as keys. If you're using an Estimator, you'll need to return a tf.train.Saver inside a tf.train.Scaffold from your model_fn.

How can I convert my model into a tflite model?
Im useing tf_vertion = 2.3 CPU
I had created the model using "model_main_tf2.py" and used "ssd_mobilenet_v2_320x320_coco17_tpu-8" pre-trained model from the tf2 model zoo.

Thank you.

**Comment by ravikyram** [comment]
@yahiya6006 

Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f1a85a8be8c1fdc5ae09e5988c76ca8d/untitled261.ipynb) for converting ssd_mobilenet_v2_320x320_coco17_tpu-8" into tflite model.Thanks!

**Comment by ichitaka** [comment]
@ravikyram The conversion is working that way but at least for me, this messed up my model.
>     input_shape = input_details[0]['shape']
>     print(input_shape)
[1 1 1 3]

Instead of the [1 320 320 1] I will get before conversion.

**Comment by yahiya6006** [comment]
@ravikyram I did the procedure which you have mentioned but I'm getting the error something related to TOCO, I'm working on my local machine and I have not installed TensorFlow-nitely. is that the issue?

**Comment by ichitaka** [comment]
@yahiya6006 I could only get the gist to work using tf-nightly.

**Comment by yahiya6006** [comment]
This is the code i used.
---------------------------------------------------------------------------------------------------
import tensorflow as tf
import os

PATH = os.getcwd()

converter = tf.lite.TFLiteConverter.from_saved_model(PATH,signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

open("model.tflite", "wb").write(tflite_model)
----------------------------------------------------------------------------------------------------------


This is the error
--------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\convert.py", line 196, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CROWN\Documents\Python\tensorflow_object_detection\object_detection\new_data\inference_graph\saved_model\cvt_tflite.py", line 10, in <module>
    tflite_model = converter.convert()
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\lite.py", line 899, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\lite.py", line 629, in convert
    result = _toco_convert_impl(
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\convert.py", line 569, in toco_convert_impl
    data = toco_convert_protos(
  File "C:\Users\CROWN\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\lite\python\convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>
--------------------------------------------------------------------------------------------------

**Comment by ichitaka** [comment]
Solution can be found here:
https://github.com/tensorflow/models/issues/9031

@yahiya6006 had the same issue, that was solved with tf-nightly.

**Comment by yahiya6006** [comment]
Thank you all for your support. I solved the problem.
-----------------------------------------------------------------------------------------------------------------------
solution: I have both python 3.7 and 3.8 installed on the machine. I trained my model using the TensorFlow object detection API. when I tried to convert it to a tflite model I was getting the error related to TOCO Converter.
According to the guidance provided above, I installed tf-nightly in a new virtual environment so that I have access to both normal TensorFlow and tf-nightly. 
This is the code which I used to convert it into a tflite model

# tf-nightly installed in a new virtual environment
import tensorflow as tf
import os

PATH = os.getcwd()
converter = tf.lite.TFLiteConverter.from_saved_model(PATH, signature_keys=['serving_default'])
print('model opened')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
print('model converted')
open("model.tflite", "wb").write(tflite_model)

Thanks once again...

**Comment by yahiya6006** [comment]
I'm still getting the error for export_tflite_ssd_graph.py and I had converted my model to tflite by skipping this step. It's not working. any solutions for this. Will it work if i skip this sep if yes then please help me out with this

**Comment by ichitaka** [comment]
@yahiya6006 Depends on what you intend to do with the file. You already have your finished tflite file, so no need to run export_tflite_ssd_graph.py and you can load the model if you have a compatible TensorFlow version.
